export default {
  // AUTH ACTION TYPES
  SET_USER: 'SET_USER',
  SET_AUTH_ERROR: 'SET_AUTH_ERROR',
  SET_AUTH_LOADING: 'SET_AUTH_LOADING',
  CLEAR_USER: 'CLEAR_USER',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN'
}
