export default {
  // AUTH ACTION TYPES
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN'
}